# **ĐỒ ÁN 02** #
### **Môn học: Toán Ứng dụng và Thống kê  -  Lớp: 21_2**
### *Họ và tên: Lê Trần Minh Khuê*
### *MSSV: 21120279*
***
### ***YÊU CẦU ĐỒ ÁN***
### **1. Viết hàm inverse(A), trong đó:**
- Input: A là ma trận vuông.
- Output: Ma trận nghịch đảo của ma trận A ban đầu (nếu có). Trường hợp không có 
ma trận nghịch đảo sẽ hiện thông báo "Ma trận không khả nghịch".   

    #### ***Lưu ý:***
    > Sinh viên phải sử dụng thuật toán Gauss – Jordan đã được hướng dẫn trong phần bài tập để tìm ma trận nghịch đảo. Sinh viên không được dùng các hàm có sẵn của các thư viện để tìm ma trận nghịch đảo.
### **2. Mở rộng:**
- Tìm hiểu hàm/ phương thức tương ứng của các thư viện và thực hiện nó, so sánh kết quả.
***

### ***GIẢI THUẬT TÌM MA TRẬN NGHỊCH ĐẢO $A^{-1}$***
##### **Bước 1:**
Lập ma trận $(A|I_n)$ có kích thước $n×2n$ là ma trận mở rộng từ ma trận A, bằng cách viết thêm ma trận đơn vị $I_n$ vào bên phải ma trận A.  
*Quy ước: Phần tử $a_{ii}$ của cột $i$ gọi là phần tử trục xoay.*
##### **Lần lượt thực hiện các bước sau cho cột thứ i (i=1,2,...,n)**
##### **Bước 2:**
Kiểm tra các số hạng từ phần tử trục xoay $a_{ii}$ của dòng i đến phần tử $a_{in}$ dòng n của cột i:
> Nếu gồm toàn số 0 $\to$ kết luận ma trận A không khả nghịch, ***giải thuật kết thúc.***  
>
> Ngược lại, đổi chỗ hai dòng (nếu cần), để đưa số hạn khác 0 nào đó ở dòng dưới thứ j về dòng thứ i.
##### **Bước 3:**
Với số hạng ở dòng thứ i là a $\neq$ 0, nhân dòng i với $\frac{1}{a}$ để nhận được số 1 (nằm trên đường chéo của A).
##### **Bước 4:** 
Cộng một bội số thích hợp của dòng i với dòng khác dòng i để biến các số hạng trên cột i về số 0 (trừ các số hạng ở dòng i). 

    Lặp lại từ bước 2 cho dòng kế tiếp, với i=i+1
***KẾT QUẢ:***
Nếu ma trận khả nghịch, ta nhận được ma trận $B=(I_n|A^{-1})$. Từ đó thu được ma trận nghịch đảo $A^{-1}$ của ma trận A.
***
### ***BÀI LÀM***

In [3]:
# ========== CÁC HÀM DÙNG ĐỂ BIẾN ĐỔI MA TRẬN ==========
# HÀM NHÂN VECTOR VỚI MỘT HẰNG SỐ
def multiply_scalar_vector(vector,scalar):
    return [scalar*a for a in vector]

# HÀM CỘNG TRỪ 2 VECTOR
def add_or_sub_vectors(vectorA,char,vectorB):
    if len(vectorA)!=len(vectorB):
        raise Exception("Error! Two vectors are not the same size.")
    else:
        respond =[]
        if char=='+':
            for i in range(len(vectorA)):
                respond.append(vectorA[i]+vectorB[i])
        elif char=='-':
            for i in range(len(vectorA)):
                respond.append(vectorA[i]-vectorB[i])
        else:
            raise Exception("Error! No valid operation found.")
        return respond

# HÀM HOÁN VỊ 2 DÒNG CỦA MA TRẬN
def rows_permutation(matrix,row1, row2):
    if row1>=len(matrix) or row2>=len(matrix):
        raise Exception("Error! Rows not exist in Matrix.")
    else:
        tempRow=matrix[row1]
        matrix[row1]=matrix[row2]
        matrix[row2]=tempRow
        return matrix

# HÀM TẠO MA TRẬN ĐƠN VỊ CẤP N
def identity_matrix(n):
    return [[1 if j == i else 0 for i in range(n)] for j in range(n)]

# HÀM KIỂM TRA MA TRẬN ĐƠN VỊ:
def is_Identity_matrix(mat):
    rows=len(mat)
    cols=len(mat[0])

    # Nếu số dòng != số cột => Kết thúc, trả kết quả False
    if rows!=cols:
        return False

    # Nếu các phần tử trên đường chéo chính != 1
    # Hoặc các phần tử còn lại != 0
    # => Kết thúc, trả kết quả False\
    for i in range(rows):
        for j in range(cols):
            if i==j and round(mat[i][j],2)!=1.00:
                return False
            if i!=j and round(mat[i][j],2)!=0.00:
                return False
    return True


In [4]:
# ==== Cách 1: VIẾT RIÊNG 3 HÀM TẠO MA TRẬN ĐƠN VỊ, GIẢI GAUSS JORDAN, VÀ INVERSE()
# Hàm inverse() nhận input là ma trận cần tìm nghịch đảo, lần lượng gọi hàm tạo A|In và hàm Gaus_Jordan, sau đó thực hiện tính toán và kết luận

# HÀM TẠO MA TRẬN A|I_n
def augmented_identity_matrix(mat):
    identity_mat=identity_matrix(len(mat))
    res=mat
    for i in range(len(mat)):
        for j in range(len(mat)):
            res[i].append(identity_mat[i][j])
    return res

# HÀM BIẾN ĐỔI MA TRẬN VÈ DẠNG BẬC THANG RÚT GỌN BẰNG GIẢI THUẬT GAUSS JORDAN
def Gauss_Jordan_elimination(mat):
    rows = len(mat)
    maxDim=len(mat[0])

    for i in range(rows):
        k=1
        while mat[i][i]==0 :
            # nếu vẫn chưa khác 0 thì tiếp tục hoán vị cho dòng bên dưới
            #   nếu không có dòng nào thoả điều kiện để hoán vị thì dừng, 
            #   trả về ma trận vừa tính được và flag = False để báo ma trận không khả nghịch
            if i+k >= rows:
                #return (mat,False)
                return mat
            mat=rows_permutation(mat,i,i+k)
            k+=1

        # Đưa phần tử trục xoay (a[i][i] hay Heading Number) về 1:
        heading = mat[i][i]
        for j in range(i,maxDim):
            mat[i][j]= mat[i][j]/heading

        # Lần lượt cộng một bội số thích hợp của dòng i với dòng khác dòng i
        # để biến các số hạng trên cột i về số 0. (trừ các số hạng ở dòng i)
        for j in range(0,rows):
            if j==i:
                continue
            alpha=-mat[j][i]
            if alpha == 0:
                continue
            mat[j]=add_or_sub_vectors(mat[j],'+',multiply_scalar_vector(mat[i],alpha))
    # Nếu đã tính xong, trả kết quả là ma trận bật thang
    return mat

def inverse_(mat):
    mat = augmented_identity_matrix(mat)
    mat = Gauss_Jordan_elimination(mat)

    size=len(mat)
    maxCols=len(mat[0])
    border = size

    res_identity=[[0 for i in range(len(mat))] for j in range(len(mat))]
    res_inv=[[0 for i in range(len(mat))] for j in range(len(mat))]

    for i in range(size):
        for j in range(maxCols):
            if j<border:
                res_identity[i][j]=mat[i][j]
            else:
                k=j-size
                res_inv[i][k]=mat[i][j]

    if is_Identity_matrix(res_identity) == False:
        print('Math Error! Matrix does not have an inverse.\nA|In matrix is:\n')
        return mat
    else:
        return res_inv


import numpy as np

# TEST VỚI MA TRẬN TẠO NGẪU NHIÊN BẰNG THƯ VIỆN NUMPY *CHỈ DÙNG THƯ VIỆN ĐỂ TẠO TESTCASE VÀ KIỂM TRA KẾT QUẢ
print('Testcase 01: Random matrix (with given size =5)\nInput:')
size=4
sampleMatrix=np.random.randint(10,size=(size, size))
sampleMatrix=sampleMatrix.reshape(size,size)
sample = [[0 for i in range(size)] for j in range(size)]
for i in range(size):
    for j in range(size):
        sample[i][j]=sampleMatrix[i][j]

# In ma trận dễ nhìn hơn:
for i in range(size):
    print(sample[i])

print('\nMy function: ')
result = inverse_(sample)
for i in range(size):
    print(result[i])

print('\nLib function:')
if (abs(np.linalg.det(sampleMatrix))<0.0000000000001):
    print('Math Error! Matrix does not have an inverse')
else:
    lib_result=np.linalg.inv(sampleMatrix)
    print(lib_result)

    if np.array(result).all()==lib_result.all():
        print('\nSame result with libary function!\n')
    else:
        print('\nDifferen result with libary function!\n')

# TEST VỚI MA TRẬN KHÔNG KHẢ NGHỊCH
testcase2=[[1,3,-4],[1,5,-1],[3,13,-6]]
size2=3

matrix2 = np.array(testcase2)

sample2 = [[0 for i in range(size2)] for j in range(size2)]
for i in range(size2):
    for j in range(size2):
        sample2[i][j]=testcase2[i][j]

print('Testcase 02: Matrix does not have an inverse.\nInput:')
# In ma trận dễ nhìn hơn:
for i in range(size2):
    print(sample2[i])

print('\nMy function: ')
result2 = inverse_(sample2)
for i in range(size2):
    print(result2[i])

print('\nLib function:')
if (abs(np.linalg.det(matrix2))<0.0000000000001):
    print('Math Error! Matrix does not have an inverse')
else:
    lib_result2=np.linalg.inv(matrix2)
    print(lib_result2)

    if np.array(result2).all()==lib_result2.all():
        print('\nSame result with libary function!\n')
    else:
        print('\nDifferen result with libary function!\n')

Testcase 01: Random matrix (with given size =5)
Input:
[1, 2, 2, 7]
[7, 6, 8, 9]
[7, 6, 8, 7]
[8, 8, 3, 8]

My function: 
[-0.8214285714285714, 1.9642857142857142, -1.7857142857142856, 0.07142857142857142]
[0.7678571428571429, -2.303571428571429, 2.0714285714285716, 0.10714285714285714]
[0.14285714285714285, -0.42857142857142855, 0.5714285714285714, -0.14285714285714285]
[-0.0, 0.5, -0.5, -0.0]

Lib function:
[[-0.82142857  1.96428571 -1.78571429  0.07142857]
 [ 0.76785714 -2.30357143  2.07142857  0.10714286]
 [ 0.14285714 -0.42857143  0.57142857 -0.14285714]
 [-0.          0.5        -0.5        -0.        ]]

Same result with libary function!

Testcase 02: Matrix does not have an inverse.
Input:
[1, 3, -4]
[1, 5, -1]
[3, 13, -6]

My function: 
Math Error! Matrix does not have an inverse.
A|In matrix is:

[1.0, 0.0, -8.5, 2.5, -1.5, 0.0]
[0.0, 1.0, 1.5, -0.5, 0.5, 0.0]
[0.0, 0.0, 0.0, -1.0, -2.0, 1.0]

Lib function:
Math Error! Matrix does not have an inverse


In [5]:

# ===== Cách 2: TỔNG HỢP TẤT CẢ VÀO HÀM INVERSE: =====
def inverse(mat):
    # Lấy các thông số từ ma trận đầu vào
    rows=len(mat)
    cols=len(mat[0])*2
    border = rows

    # TẠO MA TRẬN A|I_n:
    identity_mat=identity_matrix(rows)
    for i in range(rows):
        for j in range(rows):
            mat[i].append(identity_mat[i][j])

    # Áp dụng giải thuật Gauss Jordan:
    ##########
    flag = True
    ##########
    for i in range(rows):
        k=1
        while mat[i][i]==0 :
            # nếu vẫn chưa khác 0 thì tiếp tục hoán vị cho dòng bên dưới
            #   nếu không có dòng nào thoả điều kiện để hoán vị thì dừng, 
            #   trả về ma trận vừa tính được và flag = False để báo ma trận không khả nghịch
            if i+k >= rows:
                print('Math Error! Matrix does not have an inverse.\nA|In matrix is:\n')
                return mat
            mat=rows_permutation(mat,i,i+k)
            k+=1
        
        # Đưa phần tử trục xoay (a[i][i] hay Heading Number) về 1:
        heading = mat[i][i]
        for j in range(i,cols):
            mat[i][j]= mat[i][j]/heading

        # Lần lượt cộng một bội số thích hợp của dòng i với dòng khác dòng i
        # để biến các số hạng trên cột i về số 0. (trừ các số hạng ở dòng i)
        for j in range(0,rows):
            if j==i:
                continue
            alpha=-mat[j][i]
            if alpha == 0:
                continue
            mat[j]=add_or_sub_vectors(mat[j],'+',multiply_scalar_vector(mat[i],alpha))

    # Nếu đã tính xong, trả kết quả là ma trận bật thang
    res_identity=[[0 for i in range(rows)] for j in range(rows)]
    res_inv=[[0 for i in range(rows)] for j in range(rows)]

    for i in range(rows):
        for j in range(cols):
            if j<border:
                res_identity[i][j]=mat[i][j]
            else:
                k=j-rows
                res_inv[i][k]=mat[i][j]
    return res_inv
    


import numpy as np

# TEST VỚI MA TRẬN TẠO NGẪU NHIÊN BẰNG THƯ VIỆN NUMPY *CHỈ DÙNG THƯ VIỆN ĐỂ TẠO TESTCASE VÀ KIỂM TRA KẾT QUẢ
print('Testcase 01: Random matrix (with given size =5)\nInput:')
size=4
sampleMatrix=np.random.randint(10,size=(size, size))
sampleMatrix=sampleMatrix.reshape(size,size)
sample = [[0 for i in range(size)] for j in range(size)]
for i in range(size):
    for j in range(size):
        sample[i][j]=sampleMatrix[i][j]

# In ma trận dễ nhìn hơn:
for i in range(size):
    print(sample[i])

print('\nMy function: ')
result = inverse(sample)
for i in range(size):
    print(result[i])

print('\nLib function:')
if (abs(np.linalg.det(sampleMatrix))<0.0000000000001):
    print('Math Error! Matrix does not have an inverse')
else:
    lib_result=np.linalg.inv(sampleMatrix)
    print(lib_result)

    if np.array(result).all()==lib_result.all():
        print('\nSame result with libary function!\n')
    else:
        print('\nDifferen result with libary function!\n')

# TEST VỚI MA TRẬN KHÔNG KHẢ NGHỊCH
testcase2=[[1,3,-4],[1,5,-1],[3,13,-6]]
size2=3

matrix2 = np.array(testcase2)

sample2 = [[0 for i in range(size2)] for j in range(size2)]
for i in range(size2):
    for j in range(size2):
        sample2[i][j]=testcase2[i][j]

print('Testcase 02: Matrix does not have an inverse.\nInput:')
# In ma trận dễ nhìn hơn:
for i in range(size2):
    print(sample2[i])

print('\nMy function: ')
result2 = inverse(sample2)
for i in range(size2):
    print(result2[i])

print('\nLib function:')
if (abs(np.linalg.det(matrix2))<0.0000000000001):
    print('Math Error! Matrix does not have an inverse')
else:
    lib_result2=np.linalg.inv(matrix2)
    print(lib_result2)

    if np.array(result2).all()==lib_result2.all():
        print('\nSame result with libary function!\n')
    else:
        print('\nDifferen result with libary function!\n')

Testcase 01: Random matrix (with given size =5)
Input:
[6, 8, 5, 3]
[1, 9, 1, 4]
[6, 4, 6, 6]
[4, 7, 0, 5]

My function: 
[0.14418604651162792, -0.2604651162790698, -0.07674418604651156, 0.21395348837209302]
[0.08372093023255812, 0.09069767441860466, -0.08488372093023255, -0.02093023255813953]
[0.032558139534883734, 0.11860465116279073, 0.11976744186046506, -0.25813953488372093]
[-0.2325581395348837, 0.0813953488372093, 0.1802325581395349, 0.05813953488372092]

Lib function:
[[ 0.14418605 -0.26046512 -0.07674419  0.21395349]
 [ 0.08372093  0.09069767 -0.08488372 -0.02093023]
 [ 0.03255814  0.11860465  0.11976744 -0.25813953]
 [-0.23255814  0.08139535  0.18023256  0.05813953]]

Same result with libary function!

Testcase 02: Matrix does not have an inverse.
Input:
[1, 3, -4]
[1, 5, -1]
[3, 13, -6]

My function: 
Math Error! Matrix does not have an inverse.
A|In matrix is:

[1.0, 0.0, -8.5, 2.5, -1.5, 0.0]
[0.0, 1.0, 1.5, -0.5, 0.5, 0.0]
[0.0, 0.0, 0.0, -1.0, -2.0, 1.0]

Lib function:
Ma

### ***MÔ TẢ Ý TƯỞNG THỰC HIỆN***
#### ***1. TRÌNH TỰ:***
1. Tạo ma trận $(A|I_n)$ từ ma trận A ban đầu.
2. Bắt đầu sử dụng thuật toán Gauss - Jordan như đã trình bày ở phần đầu để tiến hành tìm ma trận nghịch đảo.
* Trong bài làm viết theo 2 cách: Mỗi công việc có 1 hàm riêng, và tất cả tập trung vào hàm inverse().
#### ***2. MÔ TẢ CÁC HÀM:***
1. Cài đặt các hàm phụ, bổ trợ cho việc biến đổi ma trận.
    - Hàm nhân vector với một hằng số.
    - Hàm cộng trừ 2 vector.
    - Hàm hoán vị 2 dòng của một ma trận.
3. Cài đặt hàm tạo ma trận đơn vị cấp n.
4. Cài đặt hàm tạo ma trận $(A|I_n)$
5. Cài đặt hàm kiểm tra ma trận có là ma trận đơn vị hay không.
6. Cài đặt hàm Gauss_elimination() (để biến đổi ma trận về dạng bậc thang rút gọn*)
7. Hàm inverse() để tìm ma trận nghịch đảo (nếu có).
