# **ĐỒ ÁN 03 - Gram-Schmidt** #
## **Môn học: Toán Ứng dụng và Thống kê  -  Lớp: 21_2**
## *Họ và tên: Lê Trần Minh Khuê*
## *MSSV: 21120279*
***
## ***YÊU CẦU***
### **1) Cho A là ma trận có thể phân rã QR. Sinh viên viết chương trình in ra ma trận Q và R, biết rằng A = QR.**
    Lưu ý: sinh viên phải sử dụng thuật toán Gram – Schmidt đã được hướng dẫn trong phần bài tập. Sinh viên không được dùng các hàm có sẵn của các thư viện để phân rã QR.
### **2) Mở rộng:**
- Tìm hiểu hàm/ phương thức tương ứng của các thư viện và thực hiện nó, so sánh kết 
quả.  
- Tìm hiểu và trình bày ứng dụng của QR decomposition
***
## ***BÀI LÀM***

### **PHẦN 1: TRÌNH BÀY GIẢI THUẬT GRAM-SCHMIDT ĐỂ PHÂN RÃ MA TRẬN A=QR**
#### &nbsp;**1.1 Giải thuật Gram-Schmidt để xây dựng họ trực giao, trực chuẩn:**  
##### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Xây dựng họ trực giao:** 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Lưu ý: Với mỗi bước sau, nếu $v_i=\overrightarrow{0}$ (với $i=1..n $) thì kết luận họ không độc lập tuyến tính và kết thúc.
+ **Bước 1:** $v_1=u_1$
+ **Bước 2:** $v_2 = u_2 − \frac{⟨u_2, v_1⟩}{∥v_1∥^{2}}v_1$.
+ **Bước 3:** $v_3 = u_3 − \frac{⟨u_3, v_1⟩}{∥v_1∥^{2}}v_1 − \frac{⟨u_3, v_2⟩}{∥v_2∥^{2}}v_2$  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;***Tổng quát*** vector $v_k$ được xác định theo công thức sau:  
##### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$v_k = u_k − \frac{⟨u_k, v_1⟩}{∥v_1∥^{2}}v_1 − \frac{⟨u_k, v_2⟩}{∥v_2∥^{2}}v_2 - ··· − \frac{⟨u_k, v_{n-1}⟩}{∥v_{n-1}∥^{2}}v_{n-1} = u_k − \Sigma_{i=1}^{n-1}\frac{⟨u_m, v_i⟩}{∥v_i∥^{2}}v_i$
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Họ các vector ${v_1, v_2, . . . , v_n}$ vừa tìm được chính là họ vector trực giao.  
##### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Xây dựng họ trực chuẩn:**  
##### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$q_1 = \frac{v_1}{∥v_1∥},  q_2 = \frac{v_2}{∥v_2∥},...$  ***Tổng quát*** vector $q_k$ được xác định theo công thức sau: $q_k = \frac{v_k}{∥v_k∥}$
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Họ các vector ${q_1, q_2, . . . , q_n}$ vừa tìm được chính là họ vector trực chuẩn. 

#### &nbsp;**1.2 Dùng giải thuật Gram-Schmidt để phân rã ma trận:**  

##### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Bước 1:** Xác định n vector $(u_1,..,u_n)$ lần lượt là n cột của ma trận $A$
##### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Bước 2:** Dùng giải thuật Gram-Schmidt để xây dựng họ trực chuẩn ${q_1, q_2, . . . , q_n}$.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Nếu các cột của A không độc lập tuyến tính thì thông báo không thể phân rã QR và kết thúc.
##### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Bước 3:** Ta lập được ma trận $Q$ gồm $n$ cột tương ứng với n vector ${q_1, q_2, . . . , q_n}$.
##### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Bước 4:** Lập ma trận $R$ kích thước $n×n$ như sau:
##### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; $R=\begin{bmatrix} ⟨u_1, q_1⟩ & ⟨u_2, q_1⟩ & ... & ⟨u_n, q_1⟩ \\ 0 & ⟨u_2, q_2⟩ & ... & ⟨u_n, q_2⟩ \\ \vdots &\vdots  & \ddots &\vdots\\ 0 & 0 & ... & ⟨u_n, q_n⟩ \end{bmatrix}$
    
### **PHẦN 2: CHƯƠNG TRÌNH**

In [12]:
# CÁC HÀM HỖ TRỢ SẼ DÙNG TRONG CHƯƠNG TRÌNH:

# HÀM KIỂM TRA VECTOR CÓ PHẢI VECTOR 0 HAY KHÔNG
def is_Zero_Vector(vec):
    for i in range(len(vec)):
        if vec[i]!=0:
            return False
    return True
# HÀM NHÂN VECTOR VỚI MỘT HẰNG SỐ
def multiply_scalar_vector(vector,scalar):
    return [scalar*a for a in vector]
# HÀM TÍNH CHUẨN VECTOR
def norm(vector):
    result =0
    for i in range(len(vector)):
        result += vector[i]**2
    return result**0.5
# HÀM CỘNG TRỪ 2 VECTOR
def add_or_sub_vectors(vectorA,char,vectorB):
    if len(vectorA)!=len(vectorB):
        print("2 input vector are not the same size.")
        return None
    else:
        respond =[]
        if char=='+':
            for i in range(len(vectorA)):
                respond.append(vectorA[i]+vectorB[i])
        elif char=='-':
            for i in range(len(vectorA)):
                respond.append(vectorA[i]-vectorB[i])
        else:
            print("Error! No valid operation found.")
            return None
        return respond
# HÀM TÍNH TÍCH VÔ HƯỚNG CỦA 2 VECTOR
def dot_product(vec1, vec2):
    if len(vec1) != len(vec2):
        print("2 input vector are not the same size.")
        return None
    result = 0
    for i in range(len(vec1)):
        result += vec1[i]*vec2[i]
    return result
# HÀM LẤY CỘT THỨ i TRONG MA TRẬN
def get_column(matrix, i):
    if i>=len(matrix[0]):
        #raise TypeError("Index out of bounds for input matrix!")
        print("Index ",i," out of bounds for input matrix!")
        return None
    result = []
    for j in matrix:
        result.append(j[i])
    return result
# HÀM LÀM TRÒN SỐ TRONG MA TRẬN ĐẾN N CHỮ SỐ THẬP PHÂN
def roundDigitsForMatrix(matrix, digits:int):
    for i in range(len(matrix)):
        temp=matrix[i]
        for k in range(len(temp)):
            temp[k]=round(temp[k],digits)
        matrix[i]=temp
    return matrix
# HÀM KIỂM TRA HAI MA TRẬN BẰNG NHAU
def isTheSame(matrix1,matrix2):
    if len(matrix1)!=len(matrix2) or len(matrix1[0])!=len(matrix2[0]):
        return False
    for i in range(len(matrix1)):
        for j in range(len(matrix1[0])):
            if matrix1[i][j]!=matrix2[i][j]:
                return False
    return True

def QR_decomposition(matrix):
    m = len(matrix)
    n = len(matrix[0])
    # ===== Xây dựng trực giao:=====
    v = []
    # vector v1=u1
    
    if is_Zero_Vector(get_column(matrix,0)):
            print("Các vector không độc lập tuyến tính. Không thể tiến hành phân rã QR!")
            #exit(0)
            return None,None,False
    v.append(get_column(matrix,0))
    # lần lượt áp dụng công thức tổng quát cho các vector sau
    for i in range(1,n):
        u = get_column(matrix,i)
        temp = u
        for j in range(0,i):
            v_j=v[j]
            scalar = dot_product(u,v_j)/(norm(v_j)**2)
            temp=add_or_sub_vectors(temp,"-",multiply_scalar_vector(v_j,scalar))
        if is_Zero_Vector(temp):
            print("Các vector không độc lập tuyến tính. Không thể tiến hành phân rã QR!")
            #exit(0)
            return None,None,False
        v.append(temp)
    # ===== Xây dựng trực chuẩn =====
    q=[]
    for i in range(len(v)):
        div_normV=1/norm(v[i])
        q.append(multiply_scalar_vector(v[i],div_normV))

    # LẬP MA TRẬN Q
    Q = [[0 for i in range(len(q))] for j in range(len(q[0]))]
    for i in range(len(q)):
        for j in range(len(q[0])):
            Q[j][i]=q[i][j]

    # LẬP MA TRẬN R
    R = [[0 for i in range(len(q))] for j in range(len(q))]
    for i in range(len(q)):
        for j in range(len(q)):
            if j<i:
                continue
            R[i][j]=dot_product(q[i],get_column(matrix,j))

    # Xử lý làm tròn số đến 5 chữ số thập phân
    v=roundDigitsForMatrix(v,5)
    q=roundDigitsForMatrix(q,5)
    Q=roundDigitsForMatrix(Q,5)
    R=roundDigitsForMatrix(R,5)

    #return v,q,Q,R
    return Q,R,True


In [13]:
# Phần kiểm thử chương trình
# Dùng thư viện numpy với phép tính @ để kiểm tra kết quả. Không tác động đến quá trình phân rã
import numpy as np
# Testcase1 là test case kích thước 3x3, có thể phân rã QR
testcase1=[[1,-1,1],[1,1,2],[1,0,1]]
print("===== Testcase 01 =====")
print("Ma trận A:")
for i in range(len(testcase1)):
    print(testcase1[i])

Q,R,flag = QR_decomposition(testcase1)
if flag:
    print("\nMa trận Q:")
    for i in range(len(Q)):
        print(Q[i])
    print("\nMa trận R:")
    for i in range(len(R)):
        print(R[i])

    print("\nKiểm tra kết quả:")
    q_ans = np.array(Q)
    shape = (len(Q),len(Q[0]))
    q_ans.reshape(shape)

    r_ans = np.array(R)
    shape = (len(R),len(R[0]))
    r_ans.reshape(shape)

    A = roundDigitsForMatrix(q_ans @ r_ans,3)
    print("Ma trận A'= QR là:")
    for i in range(len(A)):
        print(A[i])
    print("\nMa trận A' = A :", isTheSame(testcase1,A))


===== Testcase 01 =====
Ma trận A:
[1, -1, 1]
[1, 1, 2]
[1, 0, 1]

Ma trận Q:
[0.57735, -0.70711, 0.40825]
[0.57735, 0.70711, 0.40825]
[0.57735, 0.0, -0.8165]

Ma trận R:
[1.73205, 0.0, 2.3094]
[0, 1.41421, 0.70711]
[0, 0, 0.40825]

Kiểm tra kết quả:
Ma trận A'= QR là:
[ 1. -1.  1.]
[1. 1. 2.]
[1. 0. 1.]

Ma trận A' = A : True


In [14]:
# Phần kiểm thử chương trình
# Dùng thư viện numpy với phép tính @ để kiểm tra kết quả. Không tác động đến quá trình phân rã
import numpy as np
# Testcase2 là test case kích thước 4x3, có thể phân rã QR
testcase2=[[1,2,1],[-1,1,1],[1,1,1],[-1,1,1]]
print("===== Testcase 02 =====")
print("Ma trận A:")
for i in range(len(testcase2)):
    print(testcase2[i])

Q,R,flag = QR_decomposition(testcase2)
if flag:
    print("\nMa trận Q:")
    for i in range(len(Q)):
        print(Q[i])
    print("\nMa trận R:")
    for i in range(len(R)):
        print(R[i])

    print("\nKiểm tra kết quả:")
    q_ans = np.array(Q)
    shape = (len(Q),len(Q[0]))
    q_ans.reshape(shape)

    r_ans = np.array(R)
    shape = (len(R),len(R[0]))
    r_ans.reshape(shape)

    A = roundDigitsForMatrix(q_ans @ r_ans,3)
    print("Ma trận A'= QR là:")
    for i in range(len(A)):
        print(A[i])
    print("\nMa trận A' = A :", isTheSame(testcase2,A))


===== Testcase 02 =====
Ma trận A:
[1, 2, 1]
[-1, 1, 1]
[1, 1, 1]
[-1, 1, 1]

Ma trận Q:
[0.5, 0.67358, -0.54433]
[-0.5, 0.48113, 0.13608]
[0.5, 0.28868, 0.8165]
[-0.5, 0.48113, 0.13608]

Ma trận R:
[2.0, 0.5, 0.0]
[0, 2.59808, 1.9245]
[0, 0, 0.54433]

Kiểm tra kết quả:
Ma trận A'= QR là:
[1. 2. 1.]
[-1.  1.  1.]
[1. 1. 1.]
[-1.  1.  1.]

Ma trận A' = A : True


In [15]:
# Phần kiểm thử chương trình
# Dùng thư viện numpy với phép tính @ để kiểm tra kết quả. Không tác động đến quá trình phân rã
import numpy as np
# Testcase3 là test case kích thước 4x3, KHÔNG thể phân rã QR
testcase3=[[1,0,1],[-1,1,1],[1,0,1],[-1,1,1]]
print("===== Testcase 03 =====")
print("Ma trận A:")
for i in range(len(testcase3)):
    print(testcase3[i])

Q,R,flag = QR_decomposition(testcase3)
if flag:
    print("\nMa trận Q:")
    for i in range(len(Q)):
        print(Q[i])
    print("\nMa trận R:")
    for i in range(len(R)):
        print(R[i])

    print("Kiểm tra kết quả:")
    q_ans = np.array(Q)
    shape = (len(Q),len(Q[0]))
    q_ans.reshape(shape)

    r_ans = np.array(R)
    shape = (len(R),len(R[0]))
    r_ans.reshape(shape)

    A = roundDigitsForMatrix(q_ans @ r_ans,3)
    print("Ma trận A'=QR là:")
    print("A' =")
    for i in range(len(A)):
        print(A[i])
    print("\nMa trận A' = A :", isTheSame(testcase2,A))


===== Testcase 03 =====
Ma trận A:
[1, 0, 1]
[-1, 1, 1]
[1, 0, 1]
[-1, 1, 1]
Các vector không độc lập tuyến tính. Không thể tiến hành phân rã QR!


In [22]:
# MỞ RỘNG, TÍNH TOÁN BẰNG NUMPY
import numpy as np

A = np.array([[1,2,1],[-1,1,1],[1,1,1],[-1,1,1]])
Q, R = np.linalg.qr(A)

print("Ma trận A =")
print(A)
print("\nMa trận Q:")
print(Q)
print("\nMa trận R:")
print(R)

Aa = Q@R
print("Ma trận A'= QR là:")
print(Aa)


Ma trận A =
[[ 1  2  1]
 [-1  1  1]
 [ 1  1  1]
 [-1  1  1]]

Ma trận Q:
[[-0.5        -0.67357531  0.54433105]
 [ 0.5        -0.48112522 -0.13608276]
 [-0.5        -0.28867513 -0.81649658]
 [ 0.5        -0.48112522 -0.13608276]]

Ma trận R:
[[-2.         -0.5         0.        ]
 [ 0.         -2.59807621 -1.9245009 ]
 [ 0.          0.         -0.54433105]]
Ma trận A'= QR là:
[[ 1.  2.  1.]
 [-1.  1.  1.]
 [ 1.  1.  1.]
 [-1.  1.  1.]]


***Nhận xét:***  Kết quả khi dùng hàm tự viết và hàm thư viện là như nhau (Q và R ở hai kết quả ngược dấu nhau nhưng vẫn đảm bảo tích QR = A)

### **PHẦN 3: MÔ TẢ CÁC HÀM DÙNG TRONG CHƯƠNG TRÌNH**
#### &nbsp;&nbsp;&nbsp;&nbsp;**3.1 CÁC HÀM BIẾN LIÊN QUAN TỚI VECTOR**
##### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **3.1.1 Hàm kiểm tra vector có phải vector 0 hay không.**
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Hàm ***is_Zero_Vector(vector)*** nhận vào một vector, lần lượt kiểm tra các phần tử của vector này.  
>
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **Kết quả trả về:**  
>- Nếu tồn tại phần tử khác 0 thì trả về kết quả ***False*** (vector đầu vào khác vector 0).
>- Nếu tất cả phần tử đều bằng 0 thì trả về kết quả ***True*** (Vector đầu vào là vector 0).
##### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**3.1.2 Hàm nhân vector với một hằng số.**
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Hàm ***multiply_scalar_vector(vector,scalar)*** nhận vào một vector, và một hằng số (theo thứ tự). Lần lượt thực hiện nhân các phần tử của vector đầu vào với hằng số.   
>
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **Kết quả trả về:** vector sau khi đã nhân hoàn tất.

##### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **3.1.3 Hàm tính chuẩn của vector**
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Hàm ***norm(vector)*** nhận vào một vector.
>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **Kết quả trả về:** Giá trị chuẩn của vector.

##### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **3.1.4 Hàm tính tổng/ hiệu 2 vector**
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Hàm ***add_or_sub_vectors(vectorA,char,vectorB)*** nhận vào hai vector(vectorA, vector B) và 1 ký tự đóng vai trò là phép tính (char).
>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **Kết quả trả về:**  
> - Nếu 2 vector khác nhau về kích thước, in ra thông báo *"2 input vector are not the same size."* và trả về ***None***.
>- Nếu ký tự đầu vào khác "+" và "-" thì in ra thông báo *"Error! No valid operation found."* và trả về ***None***.
> - Ngược lại, trả về vector tổng/hiệu tương ứng của 2 vector đầu vào.

##### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **3.1.5 Hàm tính tích vô hướng 2 vector**
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Hàm ***dot_product(vec1, vec2)*** nhận vào hai vector(vec1 và vec2).
>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **Kết quả trả về:**  
> - Nếu 2 vector khác nhau về kích thước, in ra thông báo *"2 input vector are not the same size."* và trả về ***None***.
> - Ngược lại, trả về giá trị ***tích vô hướng*** của 2 vector đầu vào.

#### &nbsp;&nbsp;&nbsp;&nbsp;**3.2 CÁC HÀM BIẾN LIÊN QUAN TỚI MA TRẬN**
##### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **3.2.1 Hàm lấy cột thứ i của ma trận.**  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Hàm ***get_column(matrix, i)*** nhận vào ma trận *matrix* và giá trị $i$ là chỉ số của cột cần lấy. 
>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **Kết quả trả về:**  
> - Nếu i nằm ngoài phạm vi cột của ma trận, in ra thông báo *"Index i out of bounds for input matrix!"* và trả về ***None***.
> - Ngược lại, trả về ***vector cột i*** của ma trận.

##### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **3.2.2 Hàm làm tròn các giá trị trong ma trận đến n chữ số thập phân.**  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;***Lý do cần dùng hàm này:*** Trong quá trình tính toán trên kiểu dữ liệu float có thể dẫn đến một phần sai số khiến kết quả nhận được có phần chênh lệch với thực tế.   
>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Cụ thể, hàm này sẽ có tác dụng xử lý các số gần đúng như $\pm 0,99999999..\approx\pm 1$ hay $\pm 0,0000000000001...\approx\pm 0$ (Hỗ trợ cho việc kiểm tra kết quả sẽ trình bày ở phần sau) và xử lý làm tròn các số vô tỉ để dễ nhìn và đồng nhất định dạng.  
>
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Hàm ***roundDigitsForMatrix(matrix, digits:int)*** nhận vào ma trận *matrix* và giá trị *digits* là số chữ số thập phân muốn làm tròn.
> - Trong quá trình xử lý, hàm có gọi hàm round() có sẵn để làm tròn số. (Không tác động tới việc xử lý phân rã QR). 
>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **Kết quả trả về:**  
> - Ma trận matrix với các phần tử đã được làm tròn.

##### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **3.2.3 Hàm kiểm tra hai ma trận bằng nhau.**  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;***Lý do cần dùng hàm này:*** Để kiểm tra lại kết quả đã tính toán ra (Q@R) có khớp với dữ liệu nhập vào hay không. 
>
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Hàm ***isTheSame(matrix1,matrix2)*** nhận vào 2 ma trận *matrix1* và *matrix2*.
>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **Kết quả trả về:**  
> - Nếu kích thước của 2 ma trận khác nhau, hoặc kích thước của hai ma trận bằng nhau nhưng tồn tại phần tử ở cùng vị trí mang giá trị khác nhau, thì trả về ***False***.
> - Ngược lại, trả về ***True***.


#### &nbsp;&nbsp;&nbsp;&nbsp;**3.3 HÀM CHÍNH CỦA CHƯƠNG TRÌNH: QR_decomposition**
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Hàm ***QR_decomposition(matrix)*** nhận vào ma trận *matrix*.
>
>  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;***Mục tiêu:** phân rã ma trận thành ma trận Q và R (nếu được).
>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **Quá trình thực hiện:**  Lần lượt xử lý và tính toán theo giải thuật đã trình bày ở phần 1.
>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **Kết quả trả về:**  
> - Nếu phân rã QR được, output là ma trận $Q$ và $R$ theo đúng thứ tự.
> - Nếu không được, thông báo "Các vector không độc lập tuyến tính. Không thể tiến hành phân rã QR!" và output là None,None, False.
>> Khi thực thi chương trình, ta đặt flag để kiểm soát giá trị bool trong kết quả trả về:
>>- Nếu flag==False thì không thực hiện tiếp.
>> - Nếu flag == True thì tiến hành in và thực hiện kiểm tra kết quả.


### **PHẦN 4: ỨNG DỤNG**
Trong đại số tuyến tính, phân rã QR, còn được gọi là phân tích nhân tố QR hoặc phân tích nhân tố QU là phân rã ma trận A thành tích A = QR của ma trận trực giao Q và ma trận tam giác trên R. Phân rã QR thường được sử dụng để giải quyết vấn đề bình phương tối thiểu tuyến tính và là cơ sở cho một thuật toán eigenvalue cụ thể, thuật toán QR.